language: python

matrix:
  include:
    - python: 2.6
    - python: 2.7
    - python: 3.3
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: pypy
    - python: pypy3
    - python: nightly

install:
  - pip install --no-cache-dir --requirement requirements.txt

script:
  - pep8 --max-line-length=120 .
  - coverage run setup.py test
  - coverage report --include='python_skeleton/*' --fail-under=100
